PROGRAM EX
IMPLICIT NONE

 INTEGER:: DATE,YEAR,MONTH,DAY
 READ*, DATE

  YEAR=DATE/10000
  MONTH=(DATE-YEAR*10000)/100
  DAY=(DATE-YEAR*10000)-(MONTH*100)
							  
 PRINT*,YEAR,"YEAR",MONTH,"MONTH",DAY,"DAY"
  
 END PROGRAM EX
