!
!  SourceFile3.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  2014-09-26 오후 1:26:14
!
PROGRAM EXTWO

IMPLICIT NONE
REAL :: DE,HU,WI
LOGICAL :: OKAYSPRAY,A,B,C

READ*, DE,HU,WI 

 A= DE>=30
 B= HU>=15 .AND. HU<=35
 C= WI<=5

OKAYSPRAY=A .AND. B .AND. C
IF(OKAYSPRAY)PRINT*, "TRUE"

END PROGRAM EXTWO

