!
!  SourceFile2.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  2014-09-26 오후 1:20:36
!
PROGRAM EXONE
 IMPLICIT NONE
  
  INTEGER::YEAR
  READ*,YEAR
  IF(MOD(YEAR,4)/=0)THEN
   PRINT*,"NORMAL YEAR"
   ELSE IF(MOD(YEAR,100)/=0.OR.MOD(YEAR,400)==0)THEN
   PRINT*, "LEAP YEAR"
   ELSE
   PRINT*, "NORMAL YEAR"
  END IF

  END PROGRAM EXONE

