!
!  SourceFile1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  2014-10-10 오후 1:25:49
!

PROGRAM EXONE
IMPLICIT NONE
INTEGER :: I

 DO I=0,999,10
  IF(I>0) PRINT*, I
 END DO

END PROGRAM EXONE