!
!  SourceFile1.f90
!
!  Free-Format Fortran Source File 
!  Generated by PGI Visual Fortran(R)
!  2014-10-17 오후 1:05:27
!
PROGRAM EXONE
IMPLICIT NONE
INTEGER :: N=0,S=0 !N=NUMBER, S=N**2

 DO
    N=N+1
    IF(N+51<S) EXIT 
	S=N**2
	PRINT*, N,S
 END DO

END PROGRAM