  PROGRAM EXTHREE
  IMPLICIT NONE

  INTEGER :: Y,M,D,SUM=0,TSUM,I !TSUM=TOTAL SUM
  INTEGER,DIMENSION(11) :: MONTHS !CARE ABOUT DIMENSION IS 11
  
  PRINT*, "WRITE YEAR"  ; READ*, Y
  PRINT*, "WRITE MONTH" ; READ*, M
  PRINT*, "WRITE DAY"   ; READ*, D

  
 IF(MOD(Y,4)==0.AND.MOD(Y,100)/=0.OR.MOD(Y,400)==0) THEN
    IF(M==1) THEN
    PRINT*, D

    ELSE IF(M>1) THEN
    MONTHS=(/0,31,29,30,31,30,31,31,30,31,30/) !JANUARY,1DAY=1D SO MONTHS(1)=0 /AND DECEMBER(31) IS NO INCLUDE IN MONTHS 
    DO I=1,M
    SUM=SUM+MONTHS(I)
    END DO
    TSUM=SUM+D+31 !TOTALSUM=TOTAL MONTHS DAYS(EXCEPT JANUARY) + DAY + 31(JANUARY DAYS)
    PRINT*, "JULIAN DAY=", TSUM
   
    ELSE
    STOP
    END IF
 
 ELSE
  	IF(M==1) THEN
    PRINT*, D

    ELSE IF(M>1) THEN
    MONTHS=(/0,31,28,30,31,30,31,31,30,31,30/) !JANUARY,1DAY=1D SO MONTHS(1)=0 /AND DECEMBER(31) IS NO INCLUDE IN MONTHS 
    DO I=1,M
    SUM=SUM+MONTHS(I)
    END DO
    TSUM=SUM+D+31 !TOTALSUM=TOTAL MONTHS DAYS(EXCEPT JANUARY) + DAY + 31(JANUARY DAYS)
    PRINT*, "JULIAN DAY=", TSUM
   
    ELSE
    STOP
    END IF

END IF

END PROGRAM
  



  
   
