PROGRAM EXTHREE
IMPLICIT NONE

INTEGER :: LINES,L,N=0,S=0,U=0,NUMU=0,NUMS=0
REAL :: MEANS,MEANU,VARS,VARU,STDS,STDU
INTEGER,DIMENSION(:),ALLOCATABLE ::	YR,MON,DAY
REAL,DIMENSION(:),ALLOCATABLE :: TEMP,WD,WS

OPEN (1, FILE = "C:\daily_mean.txt")

 DO
   READ(1,*,END=10)
   LINES=LINES+1
  END DO
   10 CONTINUE
   L=LINES

 ALLOCATE (YR(L),MON(L),DAY(L),TEMP(L),WD(L),WS(L))
 
 REWIND(1)
 
 DO L=1,LINES
  READ(1,*) YR(L),MON(L),DAY(L),TEMP(L),WD(L),WS(L)
 END DO


 REWIND(1)


 DO L=1,LINES	

  S=S+TEMP(L)
  U=U+WS(L)
  NUMS=NUMS+TEMP(L)**2
  NUMU=NUMU+WS(L)**2
  N=N+1
 
 END DO

 MEANS=FLOAT(S)/N !FLOAT IS CHANGE REAL TO INTEGER
 MEANU=FLOAT(U)/N
 VARS=FLOAT(NUMS)/N-FLOAT(S**2)/N**2
 VARU=FLOAT(NUMU)/N-FLOAT(U**2)/N**2
 STDS=SQRT(VARS)
 STDU=SQRT(VARU)

PRINT*, MEANS,MEANU
PRINT*,	VARS,VARU
PRINT*, STDS,STDU

END PROGRAM

   


